import { useOutletContext } from "react-router-dom";
import { SubHeader } from "../components/common/SubHeader";

export const Disclaimer = () => {
  const { darkMode, setDarkMode } = useOutletContext();

  return (
    <div
      className={darkMode ? "bg-[#101214] text-white pt-18" : "bg-white pt-18 text-black"}
    >
      <SubHeader darkMode={darkMode} title="Disclaimer" />
      <div className="md:px-10 px-5 py-6 flex flex-col gap-4">
        <p className="text-[16px] leading-[160%]">
          <strong
            className={`font-bold ${darkMode ? "text-white" : "text-black"}`}
          >
            Effective Date:
          </strong>{" "}
          7 August 2025
        </p>

        <p className="text-[16px] leading-[160%]">
          <strong
            className={`font-bold ${darkMode ? "text-white" : "text-black"}`}
          >
            General Disclaimer:
          </strong>
          <br />
          Paraphraser is provided "as-is" without any warranty of any kind,
          express or implied. While we strive to provide accurate and reliable
          paraphrasing, we do not guarantee the accuracy, reliability, or
          completeness of the results generated by the app.
        </p>

        <p className="text-[16px] leading-[160%]">
          <strong
            className={`font-bold ${darkMode ? "text-white" : "text-black"}`}
          >
            Limitation of Liability:
          </strong>
          <br />
          To the fullest extent permitted by applicable law, Paraphraser is not
          responsible for any damages arising from the use or inability to use
          the app, including but not limited to loss of data, profits, or
          business opportunities.
        </p>

        <p className="text-[16px] leading-[160%]">
          <strong
            className={`font-bold ${darkMode ? "text-white" : "text-black"}`}
          >
            Use at Your Own Risk:
          </strong>
          <br />
          By using Paraphraser, you acknowledge that you use the service at your
          own risk. We recommend reviewing all paraphrased content for accuracy
          and appropriateness before use.
        </p>

        <p className="text-[16px] leading-[160%]">
          <strong
            className={`font-bold ${darkMode ? "text-white" : "text-black"}`}
          >
            No Professional Advice:
          </strong>
          <br />
          The paraphrasing output provided by the service should not be
          considered professional advice. Always consult a professional before
          relying on the content for legal, medical, or other critical matters.
        </p>
      </div>
    </div>
  );
};
